package com.politecnico.simbiosisTextil.entity.dao;

public enum TipoOferta {
    CONFECCION_MAQUINA_PLANA, CONFECCION_PANTALON, CONFECCION_ROPA_INTERIOR, CONFECCION_PARA_DAMA,CONFECCION_DE_TAPABOCAS, CONFECCION_DE_BEBE, CONFECCION_COBIJAS, SOLO_ROPA_INTERIOR_PARA_BEBE_EN_ALGODON, SE_CONFECCIONAN_MAMELUCOS, SE_CONFECCIONAN_MEDIAS_PARA_ADULTOS, SE_CONFECCIONA_DELANTALES, SE_CONFECIONA_PANTALONES, SE_CONFECCIONAN_CORTINAS;
}
